plugins:
  - jekyll-feed
  - jekyll-paginate
title: W4LKER
email: walker@w4lker.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Meu jardim digital nos confins da floresta negra do ciberespaço
baseurl: "" # the subpath of your site, e.g. /blog
url: "w4lker.com.br" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-midnight
